baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'EuCanImage Portal'
theme = "ananke"

[params]
  site_logo = "/images/logo.svg"
  background_color_class = "bg-custom-blue"

[params.Social]
  twitter = "https://x.com/EuCanImage"